name: SQLMap Penetration Testing

on:
  push:
    paths:
      - 'POST_TEST/*.txt'
      - 'GET_TEST/*.txt'
      - 'PUT_TEST/*.txt'
      - 'PATCH_TEST/*.txt'
      - 'DELETE_TEST/*.txt'

jobs:
  sqlmap-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: List all files in commit
        id: file_list
        run: |
          echo "Files changed in this commit:"
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.txt$'
          files_changed=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.txt$')
          echo "::set-output name=all_files::$(echo $files_changed)"
      
      - name: Run sqlmap on each file
        run: |
          IFS=$'\n' read -rd '' -a file_array <<< "${{ steps.file_list.outputs.all_files }}"
          for file in "${file_array[@]}"; do
            echo "Testing file: $file"
            if [[ "$file" =~ ^(POST_TEST|GET_TEST|PUT_TEST|PATCH_TEST|DELETE_TEST)/.*\.txt$ ]]; then
              echo "Running sqlmap on $file"
              python sqlmap.py -r ${{ github.workspace }}/$file --batch --random-agent
            fi
          done
