name: SQLMap Penetration Testing

on:
  push:
    paths:
      - 'POST_TEST/*.txt'
      - 'GET_TEST/*.txt'
      - 'PUT_TEST/*.txt'
      - 'PATCH_TEST/*.txt'
    paths-ignore:
      - '**/*.txt'  

jobs:
  sqlmap-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.added }}  # Checks if files were added
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Run sqlmap
        run: |
          for file in ${{ toJson(github.event.head_commit.added) }}; do
            if [[ $file == POST_TEST/*.txt || $file == GET_TEST/*.txt || $file == PUT_TEST/*.txt || $file == PATCH_TEST/*.txt ]]; then
              python sqlmap.py -r ${{ github.workspace }}/$file --batch --random-agent
            fi
          done