name: SQLMap Penetration Testing

on:
  push:
    paths:
      - 'POST_TEST/*.txt'
      - 'GET_TEST/*.txt'
      - 'PUT_TEST/*.txt'
      - 'PATCH_TEST/*.txt'
      - 'DELETE_TEST/*.txt'

jobs:
  sqlmap-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: List files changed
        run: |
          echo "Files in the commit:"
          git diff --name-only --diff-filter=A HEAD
          files_changed=$(git diff --name-only --diff-filter=A HEAD | grep '\.txt$')
          echo "TXT files added: $files_changed"
          echo "::set-output name=changed_files::$files_changed"
      
      - name: Run sqlmap on each file
        run: |
          IFS=$'\n' read -rd '' -a file_array <<< "${{ steps.files.outputs.changed_files }}"
          for file in "${file_array[@]}"; do
            echo "Testing file: $file"
            if [[ "$file" =~ ^(POST_TEST|GET_TEST|PUT_TEST|PATCH_TEST|DELETE_TEST)/.*\.txt$ ]]; then
              echo "Running sqlmap on $file"
              python sqlmap.py -r ${{ github.workspace }}/$file --batch --random-agent
            else
              echo "Skipped: $file (does not match required paths)"
            fi
          done
