name: SQLMap Penetration Testing

on:
  push:
    paths:
      - 'POST_TEST/*.txt'
      - 'GET_TEST/*.txt'
      - 'PUT_TEST/*.txt'
      - 'PATCH_TEST/*.txt'
      - 'DELETE_TEST/*.txt'

jobs:
  sqlmap-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: List .txt files in the current commit
        id: files_list
        run: |
          files_changed=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '\.txt$')
          echo "TXT files affected: $files_changed"
          echo "::set-output name=changed_files::$files_changed"

      - name: Run sqlmap on each file
        run: |
          IFS=$'\n' read -d '' -a file_array <<< "${{ steps.files_list.outputs.changed_files }}"
          for file in "${file_array[@]}"; do
            echo "Testing file: $file"
            if [[ "$file" =~ ^(POST_TEST|GET_TEST|PUT_TEST|PATCH_TEST|DELETE_TEST)/.*\.txt$ ]]; then
              echo "Running sqlmap on $file"
              python sqlmap.py -r ${{ github.workspace }}/$file --batch --random-agent
            else
              echo "Skipped: $file (does not match required paths)"
            fi
          done
