name: SQLMap Penetration Testing

on:
  push:
    paths:
      - 'POST_TEST/*.txt'
      - 'GET_TEST/*.txt'
      - 'PUT_TEST/*.txt'
      - 'PATCH_TEST/*.txt'
      - 'DELETE_TEST/*.txt'

jobs:
  sqlmap-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Print Event JSON
        run: cat $GITHUB_EVENT_PATH

      - name: Extract added files
        id: files
        run: |
          files=$(jq -r '.commits[0].added | join("\n")' $GITHUB_EVENT_PATH)
          echo "Added files: $files"
          echo "::set-output name=files::$files"
      
      - name: Run sqlmap on each file
        run: |
          added_files="${{ steps.files.outputs.files }}"
          IFS=$'\n' read -rd '' -a file_array <<< "$added_files"
          for file in "${file_array[@]}"; do
            echo "Testing file: $file"
            if [[ "$file" =~ ^(POST_TEST|GET_TEST|PUT_TEST|PATCH_TEST|DELETE_TEST)/.*\.txt$ ]]; then
              echo "Running sqlmap on $file"
              python sqlmap.py -r ${{ github.workspace }}/$file --batch --random-agent
            fi
          done
